### ISSUE TITLE
Interger overflow with discrete covariates

### ISSUE THREAD

**Issue by AnnePdM** [fsavje/quickmatch#10]
I am not sure whether this is the right place to ask this question but, as yet, there are no questions in the public domain about quickmatch.  I have been using quickmatch on a large dataset; initially with good results.  However, I augmented the dataset and am now getting an error I don't understand:

Error in (function (distances, size_constraint = NULL, type_labels = NULL,  : 
  (scclust:src/digraph_core.c:93) Too many arcs in graph (adjust the `iscc_ArcIndex` type).

This is the code that I have written:

```
dist.english.state <- distances(english.state, dist_variables = c("season.num", "gender.num", "IDACI"))
match.english <- quickmatch(dist.english.state, english.state$mod.lin)
```
The dataset english.state has 4300441 records and the data are distributed well amongst the covariates and the "treatment"; the variable mod.lin.  Any suggestions?

**Comment by fsavje** [comment]
Hi @AnnePdM, and thank you for reaching out! This is a good place to ask questions like this. I'm glad that the package worked well initially -- I'll try to help you get this sorted.

The error you got indicates that the matching constraints would risk running into an integer overflow problems. Such error should, however, not pop up until one has several billion of observations or very complicated matching constraints. I suspect the problem is that `english.state$mod.lin` is not correctly coerced by the package. If it, for example, produces a lot of treatment conditions (i.e., a unique treatment for each unit), the package would spit out errors like these.

Could you please run and report the result of the following code: `nlevels(as.factor(english.state$mod.lin))`

**Comment by AnnePdM** [comment]
This is the output that I get:

>> nlevels(as.factor(english.state$mod.lin))
[1] 2

**Comment by fsavje** [comment]
Oh, that's strange. Does the error pop up when you run the following code?

```R
library("quickmatch")
set.seed(123456789)
test_data <- data.frame(season.num = rnorm(4300441),
                        gender.num = rnorm(4300441),
                        IDACI = rnorm(4300441),
                        mod.lin = rbinom(4300441, 1, 0.5))
test_dist <- distances(test_data, dist_variables = c("season.num", "gender.num", "IDACI"))
test_match <- quickmatch(test_dist, test_data$mod.lin)
```

**Comment by AnnePdM** [comment]
This works fine.  I have had a look at the covariate to see whether they are causing the problem.  This is a crosstab of the covariates:

table(english.state$IDACI, english.state$season.num, english.state$gender.num, english.state$mod.lin, useNA = "ifany")

, ,  = 0,  = Linear

          0      1
  1   86449  24846
  2   99859  25459
  3  127270  26576
  4  123608  23211
  5  132277  21427
  6  136235  22487
  7  130868  20041
  8  126179  20209
  9  145766  18197
  10 136085  20369

 
, ,  = 1,  = Linear

          0      1
  1   88179  26024
  2   93322  23538
  3  118213  26136
  4  121555  22765
  5  141209  22523
  6  138769  21653
  7  129772  20653
  8  139274  22046
  9  148277  20002
  10 135170  21884

 
, ,  = 0,  = Modular

          0      1
  1   45840   4732
  2   50688   6058
  3   60763   6731
  4   68984   6882
  5   60986   7186
  6   63917   8778
  7   58965   7019
  8   62837   6640
  9   65699   9483
  10  58718   8018

, ,  = 1,  = Modular
          0      1
  1   48639   3932
  2   50600   5566
  3   61469   6416
  4   67564   6034
  5   66637   6561
  6   65165   7958
  7   59630   6446
  8   68888   6507
  9   68782   8882
  10  59397   8062

**Comment by fsavje** [comment]
@AnnePdM The problem is caused by your covariates. The default options for `quickmatch` are tuned to the case where there's at least one continuous covariate (as that's the most common case, and also the hardest to derive good matches for). In particular, the package exploits that units don't tend to be at equal distance from each other when there's a continuous covariate. With discrete and well-populated data -- as in your case -- a lot of units will be exactly at equal distance from each other. With the default settings, the package needs to use a lot of memory to capture all that information.

There are several ways to solve the problem. First, you can change how `quickmatch` constructs matches. For example, these settings will work better in your case:

```R
dist.english.state <- distances(english.state, dist_variables = c("season.num", "gender.num", "IDACI"))
match.english <- quickmatch(dist.english.state, english.state$mod.lin, seed_method = "lexical", secondary_radius = "no_radius")
```

Second, you can perturb the data slightly to avoid identical units. If the perturbation is small relative to the distances from the real covariates, the performance penalty will be negligible. I.e.:

```R
english.state$perturbation <- runif(4300441, min = 0, max = 0.1)
dist.english.state <- distances(english.state, dist_variables = c("season.num", "gender.num", "IDACI", "perturbation"))
match.english <- quickmatch(dist.english.state, english.state$mod.lin)
```

Third, since all covariate values are populated by observations from both treatment conditions in your data, you can do exact matching. This will be superior to all other matching methods (including `quickmatch`) both with respect to speed and performance -- it will, however, not work if you add continuous covariates or discrete covariates that make some cells empty. The simplest way to derive exact matching is probably:

```R
matching <- as.integer(interaction(english.state$season.num, english.state$gender.num, english.state$IDACI))
```

Please let me know how this works for you.

**Comment by AnnePdM** [comment]
I am sure that is the reason.  The difference between the initial examples which I used (and which worked perfectly) and the subsequent one that I showed you is that I removed a continuous covariate from the mix.  Thanks so much for your help.  I will try all of your suggestions but it seems that the last is probably the most appropriate.

Once again, many thanks.

Anne

**Comment by AnnePdM** [comment]
I know this is somewhat beyond my original issue but I wondered whether I could just confirm that I have effected an exact match correctly. I have used the code you suggested to create a single variable which works in the way a propensity score might in more complex matching:

 

  first.result.school$matching <- as.integer(interaction(first.result.school$season.num, first.result.school$gender.num,

                                                         first.result.school$IDACI))

  

# Use this variable to create weights within the groups so that each group is weighted as one.

 

  weights <- ddply(first.result.school,.(matching, mod.lin), summarize, weight = 1/length(mod.lin))

  first.result.school <- data.table(first.result.school)

  weights <- data.table(weights)

  

  first.result.school <- merge(first.result.school, weights, by = c("matching", "mod.lin"), all.x = TRUE)

 

I have then used these weights in comparisons of means between the treatment and control (mod.lin).  Do that sound right?

Many thanks

Anne

**Comment by fsavje** [comment]
@AnnePdM As you note, it's beyond the scope of this forum to discuss implementations of exact matching. I recall that Imbens & Rubin have a fairly detailed discussion about it in [their book](https://www.cambridge.org/core/books/causal-inference-for-statistics-social-and-biomedical-sciences/71126BE90C58F1A431FE9B2DD07938AB). In summary, the simplest way to implement an estimator for exact matching is to calculate a simple difference-in-means treatment effect estimate within each cell/strata and then average the cell-level effects with appropriate weights (e.g., cell size or number of treated in the cells) to a sample-level estimate. A numerically identical way of doing that is to first derive unit-level weights akin to propensity scores and derive an average using the weights. The latter seems to be the route you're taking which, in that case, should be fine (but I haven't checked your code).

Good luck with your project!
