### ISSUE TITLE
Possible to create a 1:1 matching list with this package?

### ISSUE THREAD

**Issue by amedcalf** [fsavje/quickmatch#15]
Hi. Thank you for creating this great package! The flexibility and speed of this compared to other methods of matching on large datasets is incredible. 

This is a feature question rather than an issue. I was wondering if it is valid / possible to use a similar method to produce k:k matching between participants.

For example if I have 500k people in my test group and 20 million potential controls, then I would like to match each of the 500k people in my test group to the most similar 500k out of the 20 million possible controls.

(Of course in this example this means that 19.5 million controls are discarded . I understand this loses potentially valuable information and therefore likely not be best practice...but curious if in theory it's possible. 1:1 matching seems popular in some circles!)

Already your software provides a list of participant IDs to cluster IDs in the results of quickmatch(), so in my mind one approach might be to ensure each cluster contained at least the same number of controls as test participants. Then I can just take the test participants from the cluster and their nearest control participant from the same cluster.

If there was a way to set a maximum number of assignments in a similar way to the treatment_constraints parameter that sets a minimum that might work.

Do you think this is a valid approach? Either way, thanks again for creating such useful software.

**Comment by fsavje** [comment]
Hi @amedcalf !

Thanks for your kind words.

Quickmatch is not made to construct 1:1 matchings. It might be possible to repurpose the algorithm to construct such matchings, but I would not recommend it. The reason for this is that 1:1 matchings are easier to create than the type of matchings that quickmatch is made to create, so taking the detour to quickmatch will make both speed and performance worse.

If you are OK to have 1:1 matching _with_ replacement, then you can use the `nearest_neighbor_search()` function in the `distances` package (which is another of my packages, and the quickmatch package uses some of its functionality). The point of the `distances` package is that you don't need to calculate the whole distance matrix (which in your case would have 0.5M * 19.5M elements). The `nearest_neighbor_search()` function is a wrapper for the [ANN library](http://www.cs.umd.edu/~mount/ANN/) by David Mount and Sunil Arya. You would use `query_indices` and `search_indices` to tell the function that you want to match the people in the test group (`query_indices`) with the controls (`search_indices`). The output of this is a matching so that each test person is matched with exactly one control person. However, two or more different test people could be to the same control person (hence "with replacement").

If you want 1:1 matching _without_ replacement, meaning that each test person is matched with a unique control person, then things get more complicated. You could do an initial matching with replacement, and then rerun the matching for the subset of units who have collisions until you get unique matches. This would be akin to greedy matching without replacement, and it would not be optimal. There are optimal matching without replacement algorithms (e.g., the `optmatch` package), but they will generally be too slow to run on a data set of your size. For most purposes, matching with replacement is a better option than matching without replacement, both for computational speed and statistical performance. It is common to think that matching without replacement is better because it drops fewer controls, but that intuition is in many cases misguided: https://academic.oup.com/biomet/article/109/2/551/6308304

I hope this helps. Good luck with your project!

Fredrik

**Comment by adammedcalf-ww** [comment]
Thanks so much @fsavje for the very quick reply! 

That's great. I've tried my example with the `nearest_neighbor_search` function and it worked very quickly, just as you said.  I can see how I could create a greedy matching algorithm around that if I really needed without replacement. I had not known whether with or without replacement was better so I'm grateful too for your advice that with replacement is usually superior.

My next task could be to try and generalise it to work in more than 2 groups  (similar to to how your quickmatch function works). 

So if I have 1 million people in group A, 5 million in group B and 10 million in group C, I'd like to find the 1 million people in each of the groups that are most similar. 

Intuitively I could get the nearest matches between A and B, and then the nearest matches between A and C, and combine them for a rough answer. But that's probably akin what you refer to in your associate paper as investigators "using ad hoc methods which may produce matchings of poor quality" :) so I need to think more on that!

From the paper, I also wanted to say thanks for making your data and code available so we can recreate the analysis from the paper. That was very helpful to help me understand.

**Comment by fsavje** [comment]
Hi again Adam,

I'm glad it was useful, and that you found the replication code useful!

Indeed, combining two matching like that is one of the "ad hoc methods". If the only thing you're interested is the comparisons A-B and A-C, that approach is reasonable. But you don't need to combine the groups to do that. However, if you want to do the comparison B-C (directly or indirectly), then you might get a poorly performing matchings. The key issue is that we miss opportunities where we can make the matching B-C very much better by only making the matchings A-B and A-C slightly worse. However, given your sample sizes and the fact that you're doing 1:1 matchings (i.e., small groups), this should not be a huge concern.

An alternative way to do this is to use the `primary_data_points` parameter in the `sc_clustering()` function in the `scclust` package (which is the clustering function that does most of the hard work in quickmatch). If you set `primary_data_points` to group A, but still include groups B and C as size constraints, you will end up with matched groups that contain at least one unit from each of groups A, B and C, and all units from group A is matched, but units from groups B and C are only matched if it is necessary to satisfy the constraints. This will retain the approximate optimality properties of the original algorithm. (However, given your setting, the "ad hoc" approach would probably not do much worse.)

Fredrik

**Comment by amedcalf** [comment]
Thanks again @fsavje ! I've now experimented with `sc_clustering()`  like you suggested and that works great.

My only decision is in my example above, if I end up with a cluster including 3 people from A, and just 2 from B and C, how to get a k:k balance of members.

I suppose something similar to a "with replacement" selection would be to simply pick randomly from the 2 Bs and 2Cs inside the cluster until I had 3 entries. That way I have 3 from each group.

I I needed a "without replacement" version I suppose I could just discard one of the As, and then all groups have the same numbers. But as you noted above, usually that might be worse.  (And of course it loses more potential information but with the sort of sample sizes we have been discussing that's probably not a big problem if done at random!)

And in any case longer term I should probably encourage the use of the weighting methods, as your original quickmatch does!

Thanks again for all the info you provided. Would it be acceptable if sometime I make a blog post consolidating what I learned? Of course with all credit to you for the package, the paper and your help here.

**Comment by fsavje** [comment]
@amedcalf Of course, I would be delighted if you wrote a blog post about your investigations into this. Please send me a ping when you've posted it.

**Comment by amedcalf** [comment]
Hi @fsavje ,

Thanks again for all the help you gave me above. I wanted to let you know I finished the blog post I mentioned in case it was of interest, mainly based on your paper, documentation and all the help you provided above.

It ended up being quite long so I don't expect you would necessarily want to read it :) but if of interest it's [here](https://dabblingwithdata.amedcalf.com/2022/11/20/a-super-fast-and-flexible-near-optimal-matching-method-using-the-quickmatch-library-in-r/). Of course if you do check it out and see any mistakes I'd love to know.

**Comment by fsavje** [comment]
Hi @amedcalf !

Please excuse the slow reply. That's an amazingly well-written and detailed blog post. I'll surely be sending this around to people who are interested in the package. Thank you for putting it together!

Best,
Fredrik

**Comment by amedcalf** [comment]
Thanks @fsavje for the kind comments! It was a pleasure. Thanks again for creating the package, paper and your help with my questions here!
